name: daily mets data and bluesky post

on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * *' # This runs it automatically at 11am ET every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas requests beautifulsoup4 lxml atproto pytz

      - name: Run Scraper
        run: python scraper.py

      - name: Run Poster
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
        run: python poster.py

      - name: Commit updated data
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add game_number.txt mets_batters.csv
          git commit -m "Update game number and roster data" || echo "No changes to commit"
          git push
